services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=assembleia'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'

  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/assembleia'
      - 'SPRING_DATASOURCE_USERNAME=user'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
      - 'SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQLDialect'
